// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of DogbreedsLetterA_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class DogbreedsLetterA_DetailViewModel : ViewModelsBase.VMBase, IViewModels.IDogbreedsLetterA_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.DogbreedsLetterA_DogbreedsLetterA _dogbreedsLetterA_DogbreedsLetterA;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="DogbreedsLetterA_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dogbreedsLetterA_DogbreedsLetterA">The Dogbreeds Letter A_ Dogbreeds Letter A.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public DogbreedsLetterA_DetailViewModel(Repositories.DogbreedsLetterA_DogbreedsLetterA dogbreedsLetterA_DogbreedsLetterA, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_dogbreedsLetterA_DogbreedsLetterA = dogbreedsLetterA_DogbreedsLetterA;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private Entities.DogbreedsLetterASchema _currentDogbreedsLetterASchema;

        /// <summary>
        /// CurrentDogbreedsLetterASchema property.
        /// </summary>		
        public Entities.DogbreedsLetterASchema CurrentDogbreedsLetterASchema
        {
            get
            {
				return _currentDogbreedsLetterASchema;
            }
            set
            {
                SetProperty(ref _currentDogbreedsLetterASchema, value);
            }
        }
	
		private bool _hasNextpanoramaDogbreedsLetterA_Detail0;

        /// <summary>
        /// HasNextpanoramaDogbreedsLetterA_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramaDogbreedsLetterA_Detail0
        {
            get
            {
				return _hasNextpanoramaDogbreedsLetterA_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramaDogbreedsLetterA_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramaDogbreedsLetterA_Detail0;

        /// <summary>
        /// HasPreviouspanoramaDogbreedsLetterA_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramaDogbreedsLetterA_Detail0
        {
            get
            {
				return _hasPreviouspanoramaDogbreedsLetterA_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramaDogbreedsLetterA_Detail0, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechDogbreedsLetterA_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechDogbreedsLetterA_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentDogbreedsLetterASchema.Subtitle + " " + CurrentDogbreedsLetterASchema.Description);
        }
		

        private ICommand _textToSpeechDogbreedsLetterA_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechDogbreedsLetterA_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechDogbreedsLetterA_DetailStaticControlCommand
        {
            get { return _textToSpeechDogbreedsLetterA_DetailStaticControlCommand = _textToSpeechDogbreedsLetterA_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechDogbreedsLetterA_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareDogbreedsLetterA_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareDogbreedsLetterA_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentDogbreedsLetterASchema.Subtitle, CurrentDogbreedsLetterASchema.Description, "", CurrentDogbreedsLetterASchema.Image);
        }
		

        private ICommand _shareDogbreedsLetterA_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareDogbreedsLetterA_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareDogbreedsLetterA_DetailStaticControlCommand
        {
            get { return _shareDogbreedsLetterA_DetailStaticControlCommand = _shareDogbreedsLetterA_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareDogbreedsLetterA_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartDogbreedsLetterA_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartDogbreedsLetterA_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.IDogbreedsLetterA_DetailViewModel), CreateTileInfoDogbreedsLetterA_DetailStaticControl());
        }
		

        private ICommand _pinToStartDogbreedsLetterA_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartDogbreedsLetterA_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartDogbreedsLetterA_DetailStaticControlCommand
        {
            get { return _pinToStartDogbreedsLetterA_DetailStaticControlCommand = _pinToStartDogbreedsLetterA_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartDogbreedsLetterA_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the NextpanoramaDogbreedsLetterA_Detail0 command.
        /// </summary>
        public  void NextpanoramaDogbreedsLetterA_Detail0Delegate() 
        {
			var next =  _dogbreedsLetterA_DogbreedsLetterA.Next(CurrentDogbreedsLetterASchema);

			if(next != null)
				CurrentDogbreedsLetterASchema = next;

			RefreshHasPrevNext();
        }
		

        private ICommand _nextpanoramaDogbreedsLetterA_Detail0;

        /// <summary>
        /// Gets the NextpanoramaDogbreedsLetterA_Detail0 command.
        /// </summary>
        public ICommand NextpanoramaDogbreedsLetterA_Detail0
        {
            get { return _nextpanoramaDogbreedsLetterA_Detail0 = _nextpanoramaDogbreedsLetterA_Detail0 ?? new ViewModelsBase.DelegateCommand(NextpanoramaDogbreedsLetterA_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the PreviouspanoramaDogbreedsLetterA_Detail0 command.
        /// </summary>
        public  void PreviouspanoramaDogbreedsLetterA_Detail0Delegate() 
        {
			var prev =  _dogbreedsLetterA_DogbreedsLetterA.Previous(CurrentDogbreedsLetterASchema);

			if(prev != null)
				CurrentDogbreedsLetterASchema = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramaDogbreedsLetterA_Detail0;

        /// <summary>
        /// Gets the PreviouspanoramaDogbreedsLetterA_Detail0 command.
        /// </summary>
        public ICommand PreviouspanoramaDogbreedsLetterA_Detail0
        {
            get { return _previouspanoramaDogbreedsLetterA_Detail0 = _previouspanoramaDogbreedsLetterA_Detail0 ?? new ViewModelsBase.DelegateCommand(PreviouspanoramaDogbreedsLetterA_Detail0Delegate); }
        }

        private void RefreshHasPrevNext()
        {
            HasPreviouspanoramaDogbreedsLetterA_Detail0 = _dogbreedsLetterA_DogbreedsLetterA.HasPrevious(CurrentDogbreedsLetterASchema);
			HasNextpanoramaDogbreedsLetterA_Detail0 = _dogbreedsLetterA_DogbreedsLetterA.HasNext(CurrentDogbreedsLetterASchema);
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is Entities.DogbreedsLetterASchema)) { return; }
                
                CurrentDogbreedsLetterASchema = value as Entities.DogbreedsLetterASchema;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the DogbreedsLetterA_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoDogbreedsLetterA_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentDogbreedsLetterASchema.Id.ToString(),
                Title = CurrentDogbreedsLetterASchema.Subtitle,
                BackTitle = CurrentDogbreedsLetterASchema.Subtitle,
                BackContent = CurrentDogbreedsLetterASchema.Description,
                Count = 0,
                BackgroundImagePath = CurrentDogbreedsLetterASchema.Image,
                BackBackgroundImagePath = CurrentDogbreedsLetterASchema.Image,
                LogoPath = "Item-46655a22-e9de-4ba1-8c70-bb036184cb54.png"
            };
            return tileInfo;
        }
    }
}
