// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of DogbreedsLetterC_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class DogbreedsLetterC_DetailViewModel : ViewModelsBase.VMBase, IViewModels.IDogbreedsLetterC_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.DogbreedsLetterC_DogbreedsLetterC _dogbreedsLetterC_DogbreedsLetterC;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="DogbreedsLetterC_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dogbreedsLetterC_DogbreedsLetterC">The Dogbreeds Letter C_ Dogbreeds Letter C.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public DogbreedsLetterC_DetailViewModel(Repositories.DogbreedsLetterC_DogbreedsLetterC dogbreedsLetterC_DogbreedsLetterC, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_dogbreedsLetterC_DogbreedsLetterC = dogbreedsLetterC_DogbreedsLetterC;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private Entities.DogbreedsLetterCSchema _currentDogbreedsLetterCSchema;

        /// <summary>
        /// CurrentDogbreedsLetterCSchema property.
        /// </summary>		
        public Entities.DogbreedsLetterCSchema CurrentDogbreedsLetterCSchema
        {
            get
            {
				return _currentDogbreedsLetterCSchema;
            }
            set
            {
                SetProperty(ref _currentDogbreedsLetterCSchema, value);
            }
        }
	
		private bool _hasNextpanoramaDogbreedsLetterC_Detail0;

        /// <summary>
        /// HasNextpanoramaDogbreedsLetterC_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramaDogbreedsLetterC_Detail0
        {
            get
            {
				return _hasNextpanoramaDogbreedsLetterC_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramaDogbreedsLetterC_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramaDogbreedsLetterC_Detail0;

        /// <summary>
        /// HasPreviouspanoramaDogbreedsLetterC_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramaDogbreedsLetterC_Detail0
        {
            get
            {
				return _hasPreviouspanoramaDogbreedsLetterC_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramaDogbreedsLetterC_Detail0, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechDogbreedsLetterC_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechDogbreedsLetterC_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentDogbreedsLetterCSchema.Subtitle + " " + CurrentDogbreedsLetterCSchema.Description);
        }
		

        private ICommand _textToSpeechDogbreedsLetterC_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechDogbreedsLetterC_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechDogbreedsLetterC_DetailStaticControlCommand
        {
            get { return _textToSpeechDogbreedsLetterC_DetailStaticControlCommand = _textToSpeechDogbreedsLetterC_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechDogbreedsLetterC_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareDogbreedsLetterC_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareDogbreedsLetterC_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentDogbreedsLetterCSchema.Subtitle, CurrentDogbreedsLetterCSchema.Description, "", CurrentDogbreedsLetterCSchema.Image);
        }
		

        private ICommand _shareDogbreedsLetterC_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareDogbreedsLetterC_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareDogbreedsLetterC_DetailStaticControlCommand
        {
            get { return _shareDogbreedsLetterC_DetailStaticControlCommand = _shareDogbreedsLetterC_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareDogbreedsLetterC_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartDogbreedsLetterC_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartDogbreedsLetterC_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.IDogbreedsLetterC_DetailViewModel), CreateTileInfoDogbreedsLetterC_DetailStaticControl());
        }
		

        private ICommand _pinToStartDogbreedsLetterC_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartDogbreedsLetterC_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartDogbreedsLetterC_DetailStaticControlCommand
        {
            get { return _pinToStartDogbreedsLetterC_DetailStaticControlCommand = _pinToStartDogbreedsLetterC_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartDogbreedsLetterC_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the NextpanoramaDogbreedsLetterC_Detail0 command.
        /// </summary>
        public  void NextpanoramaDogbreedsLetterC_Detail0Delegate() 
        {
			var next =  _dogbreedsLetterC_DogbreedsLetterC.Next(CurrentDogbreedsLetterCSchema);

			if(next != null)
				CurrentDogbreedsLetterCSchema = next;

			RefreshHasPrevNext();
        }
		

        private ICommand _nextpanoramaDogbreedsLetterC_Detail0;

        /// <summary>
        /// Gets the NextpanoramaDogbreedsLetterC_Detail0 command.
        /// </summary>
        public ICommand NextpanoramaDogbreedsLetterC_Detail0
        {
            get { return _nextpanoramaDogbreedsLetterC_Detail0 = _nextpanoramaDogbreedsLetterC_Detail0 ?? new ViewModelsBase.DelegateCommand(NextpanoramaDogbreedsLetterC_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the PreviouspanoramaDogbreedsLetterC_Detail0 command.
        /// </summary>
        public  void PreviouspanoramaDogbreedsLetterC_Detail0Delegate() 
        {
			var prev =  _dogbreedsLetterC_DogbreedsLetterC.Previous(CurrentDogbreedsLetterCSchema);

			if(prev != null)
				CurrentDogbreedsLetterCSchema = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramaDogbreedsLetterC_Detail0;

        /// <summary>
        /// Gets the PreviouspanoramaDogbreedsLetterC_Detail0 command.
        /// </summary>
        public ICommand PreviouspanoramaDogbreedsLetterC_Detail0
        {
            get { return _previouspanoramaDogbreedsLetterC_Detail0 = _previouspanoramaDogbreedsLetterC_Detail0 ?? new ViewModelsBase.DelegateCommand(PreviouspanoramaDogbreedsLetterC_Detail0Delegate); }
        }

        private void RefreshHasPrevNext()
        {
            HasPreviouspanoramaDogbreedsLetterC_Detail0 = _dogbreedsLetterC_DogbreedsLetterC.HasPrevious(CurrentDogbreedsLetterCSchema);
			HasNextpanoramaDogbreedsLetterC_Detail0 = _dogbreedsLetterC_DogbreedsLetterC.HasNext(CurrentDogbreedsLetterCSchema);
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is Entities.DogbreedsLetterCSchema)) { return; }
                
                CurrentDogbreedsLetterCSchema = value as Entities.DogbreedsLetterCSchema;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the DogbreedsLetterC_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoDogbreedsLetterC_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentDogbreedsLetterCSchema.Id.ToString(),
                Title = CurrentDogbreedsLetterCSchema.Subtitle,
                BackTitle = CurrentDogbreedsLetterCSchema.Subtitle,
                BackContent = CurrentDogbreedsLetterCSchema.Description,
                Count = 0,
                BackgroundImagePath = CurrentDogbreedsLetterCSchema.Image,
                BackBackgroundImagePath = CurrentDogbreedsLetterCSchema.Image,
                LogoPath = "Item-46655a22-e9de-4ba1-8c70-bb036184cb54.png"
            };
            return tileInfo;
        }
    }
}
