// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of DogbreedsLetterA_List ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class DogbreedsLetterA_ListViewModel : ViewModelsBase.VMBase, IViewModels.IDogbreedsLetterA_ListViewModel
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ILockScreenService _lockScreenService;
		private readonly Repositories.IDogbreedsLetterA_DogbreedsLetterA _dogbreedsLetterA_DogbreedsLetterA;
		private readonly Repositories.IDogbreedsLetterB_DogbreedsLetterB _dogbreedsLetterB_DogbreedsLetterB;
		private readonly Repositories.IDogbreedsLetterC_DogbreedsLetterC _dogbreedsLetterC_DogbreedsLetterC;
		private readonly Repositories.IDogbreedsLetterD_DogbreedsLetterD _dogbreedsLetterD_DogbreedsLetterD;
		private readonly Repositories.IDogbreedsLetterE_DogbreedsLetterE _dogbreedsLetterE_DogbreedsLetterE;
		private readonly IServices.IInternetService _internetService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="DogbreedsLetterA_ListViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="lockScreenService">The Lock Screen Service.</param>
        /// <param name="dogbreedsLetterA_DogbreedsLetterA">The Dogbreeds Letter A_ Dogbreeds Letter A.</param>
        /// <param name="dogbreedsLetterB_DogbreedsLetterB">The Dogbreeds Letter B_ Dogbreeds Letter B.</param>
        /// <param name="dogbreedsLetterC_DogbreedsLetterC">The Dogbreeds Letter C_ Dogbreeds Letter C.</param>
        /// <param name="dogbreedsLetterD_DogbreedsLetterD">The Dogbreeds Letter D_ Dogbreeds Letter D.</param>
        /// <param name="dogbreedsLetterE_DogbreedsLetterE">The Dogbreeds Letter E_ Dogbreeds Letter E.</param>
        /// <param name="internetService">The Internet Service.</param>
        public DogbreedsLetterA_ListViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ILockScreenService lockScreenService, Repositories.IDogbreedsLetterA_DogbreedsLetterA dogbreedsLetterA_DogbreedsLetterA, Repositories.IDogbreedsLetterB_DogbreedsLetterB dogbreedsLetterB_DogbreedsLetterB, Repositories.IDogbreedsLetterC_DogbreedsLetterC dogbreedsLetterC_DogbreedsLetterC, Repositories.IDogbreedsLetterD_DogbreedsLetterD dogbreedsLetterD_DogbreedsLetterD, Repositories.IDogbreedsLetterE_DogbreedsLetterE dogbreedsLetterE_DogbreedsLetterE, IServices.IInternetService internetService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_lockScreenService = lockScreenService;
			_dogbreedsLetterA_DogbreedsLetterA = dogbreedsLetterA_DogbreedsLetterA;
			_dogbreedsLetterB_DogbreedsLetterB = dogbreedsLetterB_DogbreedsLetterB;
			_dogbreedsLetterC_DogbreedsLetterC = dogbreedsLetterC_DogbreedsLetterC;
			_dogbreedsLetterD_DogbreedsLetterD = dogbreedsLetterD_DogbreedsLetterD;
			_dogbreedsLetterE_DogbreedsLetterE = dogbreedsLetterE_DogbreedsLetterE;
			_internetService = internetService;
        }
		
	    /// <summary>
        /// IsInternetAvalaible property.
        /// </summary>		
        public Visibility IsInternetAvalaible
        {
	      get
          {
				return _internetService.IsNetworkAvailable() ? Visibility.Collapsed : Visibility.Visible; 
           }
		}
	
		private ObservableCollection<Entities.DogbreedsLetterASchema> _dogbreedsLetterA_ListListControlCollection;

        /// <summary>
        /// DogbreedsLetterA_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.DogbreedsLetterASchema> DogbreedsLetterA_ListListControlCollection
        {
            get
            {
				
                if(_dogbreedsLetterA_ListListControlCollection == null)
					_dogbreedsLetterA_ListListControlCollection = _dogbreedsLetterA_DogbreedsLetterA.GetData();
				return _dogbreedsLetterA_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _dogbreedsLetterA_ListListControlCollection, value);
            }
        }
	
		private int _dogbreedsLetterA_ListListControlCollectionPageNumber;

        /// <summary>
        /// DogbreedsLetterA_ListListControlCollectionPageNumber property.
        /// </summary>		
        public int DogbreedsLetterA_ListListControlCollectionPageNumber
        {
            get
            {
				return _dogbreedsLetterA_ListListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _dogbreedsLetterA_ListListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.DogbreedsLetterASchema _selectedDogbreedsLetterA_ListListControlCollection;

        /// <summary>
        /// SelectedDogbreedsLetterA_ListListControlCollection property.
        /// </summary>		
        public Entities.DogbreedsLetterASchema SelectedDogbreedsLetterA_ListListControlCollection
        {
            get
            {
				return _selectedDogbreedsLetterA_ListListControlCollection;
            }
            set
            {
                _selectedDogbreedsLetterA_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.IDogbreedsLetterA_DetailViewModel>(_selectedDogbreedsLetterA_ListListControlCollection);
            }
        }
	
		private ObservableCollection<Entities.DogbreedsLetterBSchema> _dogbreedsLetterB_ListListControlCollection;

        /// <summary>
        /// DogbreedsLetterB_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.DogbreedsLetterBSchema> DogbreedsLetterB_ListListControlCollection
        {
            get
            {
				
                if(_dogbreedsLetterB_ListListControlCollection == null)
					_dogbreedsLetterB_ListListControlCollection = _dogbreedsLetterB_DogbreedsLetterB.GetData();
				return _dogbreedsLetterB_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _dogbreedsLetterB_ListListControlCollection, value);
            }
        }
	
		private int _dogbreedsLetterB_ListListControlCollectionPageNumber;

        /// <summary>
        /// DogbreedsLetterB_ListListControlCollectionPageNumber property.
        /// </summary>		
        public int DogbreedsLetterB_ListListControlCollectionPageNumber
        {
            get
            {
				return _dogbreedsLetterB_ListListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _dogbreedsLetterB_ListListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.DogbreedsLetterBSchema _selectedDogbreedsLetterB_ListListControlCollection;

        /// <summary>
        /// SelectedDogbreedsLetterB_ListListControlCollection property.
        /// </summary>		
        public Entities.DogbreedsLetterBSchema SelectedDogbreedsLetterB_ListListControlCollection
        {
            get
            {
				return _selectedDogbreedsLetterB_ListListControlCollection;
            }
            set
            {
                _selectedDogbreedsLetterB_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.IDogbreedsLetterB_DetailViewModel>(_selectedDogbreedsLetterB_ListListControlCollection);
            }
        }
	
		private ObservableCollection<Entities.DogbreedsLetterCSchema> _dogbreedsLetterC_ListListControlCollection;

        /// <summary>
        /// DogbreedsLetterC_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.DogbreedsLetterCSchema> DogbreedsLetterC_ListListControlCollection
        {
            get
            {
				
                if(_dogbreedsLetterC_ListListControlCollection == null)
					_dogbreedsLetterC_ListListControlCollection = _dogbreedsLetterC_DogbreedsLetterC.GetData();
				return _dogbreedsLetterC_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _dogbreedsLetterC_ListListControlCollection, value);
            }
        }
	
		private int _dogbreedsLetterC_ListListControlCollectionPageNumber;

        /// <summary>
        /// DogbreedsLetterC_ListListControlCollectionPageNumber property.
        /// </summary>		
        public int DogbreedsLetterC_ListListControlCollectionPageNumber
        {
            get
            {
				return _dogbreedsLetterC_ListListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _dogbreedsLetterC_ListListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.DogbreedsLetterCSchema _selectedDogbreedsLetterC_ListListControlCollection;

        /// <summary>
        /// SelectedDogbreedsLetterC_ListListControlCollection property.
        /// </summary>		
        public Entities.DogbreedsLetterCSchema SelectedDogbreedsLetterC_ListListControlCollection
        {
            get
            {
				return _selectedDogbreedsLetterC_ListListControlCollection;
            }
            set
            {
                _selectedDogbreedsLetterC_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.IDogbreedsLetterC_DetailViewModel>(_selectedDogbreedsLetterC_ListListControlCollection);
            }
        }
	
		private ObservableCollection<Entities.DogbreedsLetterDSchema> _dogbreedsLetterD_ListListControlCollection;

        /// <summary>
        /// DogbreedsLetterD_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.DogbreedsLetterDSchema> DogbreedsLetterD_ListListControlCollection
        {
            get
            {
				
                if(_dogbreedsLetterD_ListListControlCollection == null)
					_dogbreedsLetterD_ListListControlCollection = _dogbreedsLetterD_DogbreedsLetterD.GetData();
				return _dogbreedsLetterD_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _dogbreedsLetterD_ListListControlCollection, value);
            }
        }
	
		private int _dogbreedsLetterD_ListListControlCollectionPageNumber;

        /// <summary>
        /// DogbreedsLetterD_ListListControlCollectionPageNumber property.
        /// </summary>		
        public int DogbreedsLetterD_ListListControlCollectionPageNumber
        {
            get
            {
				return _dogbreedsLetterD_ListListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _dogbreedsLetterD_ListListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.DogbreedsLetterDSchema _selectedDogbreedsLetterD_ListListControlCollection;

        /// <summary>
        /// SelectedDogbreedsLetterD_ListListControlCollection property.
        /// </summary>		
        public Entities.DogbreedsLetterDSchema SelectedDogbreedsLetterD_ListListControlCollection
        {
            get
            {
				return _selectedDogbreedsLetterD_ListListControlCollection;
            }
            set
            {
                _selectedDogbreedsLetterD_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.IDogbreedsLetterD_DetailViewModel>(_selectedDogbreedsLetterD_ListListControlCollection);
            }
        }
	
		private ObservableCollection<Entities.DogbreedsLetterESchema> _dogbreedsLetterE_ListListControlCollection;

        /// <summary>
        /// DogbreedsLetterE_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.DogbreedsLetterESchema> DogbreedsLetterE_ListListControlCollection
        {
            get
            {
				
                if(_dogbreedsLetterE_ListListControlCollection == null)
					_dogbreedsLetterE_ListListControlCollection = _dogbreedsLetterE_DogbreedsLetterE.GetData();
				return _dogbreedsLetterE_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _dogbreedsLetterE_ListListControlCollection, value);
            }
        }
	
		private int _dogbreedsLetterE_ListListControlCollectionPageNumber;

        /// <summary>
        /// DogbreedsLetterE_ListListControlCollectionPageNumber property.
        /// </summary>		
        public int DogbreedsLetterE_ListListControlCollectionPageNumber
        {
            get
            {
				return _dogbreedsLetterE_ListListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _dogbreedsLetterE_ListListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.DogbreedsLetterESchema _selectedDogbreedsLetterE_ListListControlCollection;

        /// <summary>
        /// SelectedDogbreedsLetterE_ListListControlCollection property.
        /// </summary>		
        public Entities.DogbreedsLetterESchema SelectedDogbreedsLetterE_ListListControlCollection
        {
            get
            {
				return _selectedDogbreedsLetterE_ListListControlCollection;
            }
            set
            {
                _selectedDogbreedsLetterE_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.IDogbreedsLetterE_DetailViewModel>(_selectedDogbreedsLetterE_ListListControlCollection);
            }
        }

        /// <summary>
        /// Delegate method for the GetDogbreedsLetterA_ListListControlCollectionCommand command.
        /// </summary>
        public  void GetDogbreedsLetterA_ListListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				GetDogbreedsLetterA_ListListControlCollectionData(pageNumber);
        }
		

        private ICommand _getDogbreedsLetterA_ListListControlCollectionCommand;

        /// <summary>
        /// Gets the GetDogbreedsLetterA_ListListControlCollectionCommand command.
        /// </summary>
        public ICommand GetDogbreedsLetterA_ListListControlCollectionCommand
        {
            get { return _getDogbreedsLetterA_ListListControlCollectionCommand = _getDogbreedsLetterA_ListListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(GetDogbreedsLetterA_ListListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GetDogbreedsLetterB_ListListControlCollectionCommand command.
        /// </summary>
        public  void GetDogbreedsLetterB_ListListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				GetDogbreedsLetterB_ListListControlCollectionData(pageNumber);
        }
		

        private ICommand _getDogbreedsLetterB_ListListControlCollectionCommand;

        /// <summary>
        /// Gets the GetDogbreedsLetterB_ListListControlCollectionCommand command.
        /// </summary>
        public ICommand GetDogbreedsLetterB_ListListControlCollectionCommand
        {
            get { return _getDogbreedsLetterB_ListListControlCollectionCommand = _getDogbreedsLetterB_ListListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(GetDogbreedsLetterB_ListListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GetDogbreedsLetterC_ListListControlCollectionCommand command.
        /// </summary>
        public  void GetDogbreedsLetterC_ListListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				GetDogbreedsLetterC_ListListControlCollectionData(pageNumber);
        }
		

        private ICommand _getDogbreedsLetterC_ListListControlCollectionCommand;

        /// <summary>
        /// Gets the GetDogbreedsLetterC_ListListControlCollectionCommand command.
        /// </summary>
        public ICommand GetDogbreedsLetterC_ListListControlCollectionCommand
        {
            get { return _getDogbreedsLetterC_ListListControlCollectionCommand = _getDogbreedsLetterC_ListListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(GetDogbreedsLetterC_ListListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GetDogbreedsLetterD_ListListControlCollectionCommand command.
        /// </summary>
        public  void GetDogbreedsLetterD_ListListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				GetDogbreedsLetterD_ListListControlCollectionData(pageNumber);
        }
		

        private ICommand _getDogbreedsLetterD_ListListControlCollectionCommand;

        /// <summary>
        /// Gets the GetDogbreedsLetterD_ListListControlCollectionCommand command.
        /// </summary>
        public ICommand GetDogbreedsLetterD_ListListControlCollectionCommand
        {
            get { return _getDogbreedsLetterD_ListListControlCollectionCommand = _getDogbreedsLetterD_ListListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(GetDogbreedsLetterD_ListListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GetDogbreedsLetterE_ListListControlCollectionCommand command.
        /// </summary>
        public  void GetDogbreedsLetterE_ListListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				GetDogbreedsLetterE_ListListControlCollectionData(pageNumber);
        }
		

        private ICommand _getDogbreedsLetterE_ListListControlCollectionCommand;

        /// <summary>
        /// Gets the GetDogbreedsLetterE_ListListControlCollectionCommand command.
        /// </summary>
        public ICommand GetDogbreedsLetterE_ListListControlCollectionCommand
        {
            get { return _getDogbreedsLetterE_ListListControlCollectionCommand = _getDogbreedsLetterE_ListListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(GetDogbreedsLetterE_ListListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the SetLockScreenCommand command.
        /// </summary>
        public  void SetLockScreenCommandDelegate() 
        {
				_lockScreenService.SetLockScreen("LockScreen-cf07aca1-a0ef-40de-93ec-03f3679ff9e4.jpg");
        }
		

        private ICommand _setLockScreenCommand;

        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
        public ICommand SetLockScreenCommand
        {
            get { return _setLockScreenCommand = _setLockScreenCommand ?? new ViewModelsBase.DelegateCommand(SetLockScreenCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the AboutCommand command.
        /// </summary>
        public  void AboutCommandDelegate() 
        {
				_navigationService.NavigateTo<IViewModels.IAboutViewModel>();
        }
		

        private ICommand _aboutCommand;

        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
        public ICommand AboutCommand
        {
            get { return _aboutCommand = _aboutCommand ?? new ViewModelsBase.DelegateCommand(AboutCommandDelegate); }
        }

        private void GetDogbreedsLetterA_ListListControlCollectionData(int pageNumber = 0)
        {
				DogbreedsLetterA_ListListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _dogbreedsLetterA_DogbreedsLetterA.GetData(pageNumber);
                    DogbreedsLetterA_ListListControlCollection = items;
				}
                else   
				{
					var items = _dogbreedsLetterA_DogbreedsLetterA.GetData(pageNumber);
                    foreach (var item in items)                    
                        DogbreedsLetterA_ListListControlCollection.Add(item);
				}
		}

        private void GetDogbreedsLetterB_ListListControlCollectionData(int pageNumber = 0)
        {
				DogbreedsLetterB_ListListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _dogbreedsLetterB_DogbreedsLetterB.GetData(pageNumber);
                    DogbreedsLetterB_ListListControlCollection = items;
				}
                else   
				{
					var items = _dogbreedsLetterB_DogbreedsLetterB.GetData(pageNumber);
                    foreach (var item in items)                    
                        DogbreedsLetterB_ListListControlCollection.Add(item);
				}
		}

        private void GetDogbreedsLetterC_ListListControlCollectionData(int pageNumber = 0)
        {
				DogbreedsLetterC_ListListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _dogbreedsLetterC_DogbreedsLetterC.GetData(pageNumber);
                    DogbreedsLetterC_ListListControlCollection = items;
				}
                else   
				{
					var items = _dogbreedsLetterC_DogbreedsLetterC.GetData(pageNumber);
                    foreach (var item in items)                    
                        DogbreedsLetterC_ListListControlCollection.Add(item);
				}
		}

        private void GetDogbreedsLetterD_ListListControlCollectionData(int pageNumber = 0)
        {
				DogbreedsLetterD_ListListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _dogbreedsLetterD_DogbreedsLetterD.GetData(pageNumber);
                    DogbreedsLetterD_ListListControlCollection = items;
				}
                else   
				{
					var items = _dogbreedsLetterD_DogbreedsLetterD.GetData(pageNumber);
                    foreach (var item in items)                    
                        DogbreedsLetterD_ListListControlCollection.Add(item);
				}
		}

        private void GetDogbreedsLetterE_ListListControlCollectionData(int pageNumber = 0)
        {
				DogbreedsLetterE_ListListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _dogbreedsLetterE_DogbreedsLetterE.GetData(pageNumber);
                    DogbreedsLetterE_ListListControlCollection = items;
				}
                else   
				{
					var items = _dogbreedsLetterE_DogbreedsLetterE.GetData(pageNumber);
                    foreach (var item in items)                    
                        DogbreedsLetterE_ListListControlCollection.Add(item);
				}
		}
    }
}
