// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// DogbreedsLetterA_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IDogbreedsLetterA_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentDogbreedsLetterASchema property.
        /// </summary>
		Entities.DogbreedsLetterASchema CurrentDogbreedsLetterASchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaDogbreedsLetterA_Detail0 property.
        /// </summary>
		bool HasNextpanoramaDogbreedsLetterA_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaDogbreedsLetterA_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaDogbreedsLetterA_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechDogbreedsLetterA_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechDogbreedsLetterA_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareDogbreedsLetterA_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareDogbreedsLetterA_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartDogbreedsLetterA_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartDogbreedsLetterA_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaDogbreedsLetterA_Detail0 command.
        /// </summary>
		ICommand NextpanoramaDogbreedsLetterA_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaDogbreedsLetterA_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaDogbreedsLetterA_Detail0 { get; }

	}
}
