// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// DogbreedsLetterD_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IDogbreedsLetterD_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentDogbreedsLetterDSchema property.
        /// </summary>
		Entities.DogbreedsLetterDSchema CurrentDogbreedsLetterDSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaDogbreedsLetterD_Detail0 property.
        /// </summary>
		bool HasNextpanoramaDogbreedsLetterD_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaDogbreedsLetterD_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaDogbreedsLetterD_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechDogbreedsLetterD_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechDogbreedsLetterD_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareDogbreedsLetterD_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareDogbreedsLetterD_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartDogbreedsLetterD_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartDogbreedsLetterD_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaDogbreedsLetterD_Detail0 command.
        /// </summary>
		ICommand NextpanoramaDogbreedsLetterD_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaDogbreedsLetterD_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaDogbreedsLetterD_Detail0 { get; }

	}
}
