// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// DogbreedsLetterA_List ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IDogbreedsLetterA_ListViewModel
    {		
	    /// <summary>
        /// IsInternetAvalaible property.
        /// </summary>		
        Visibility IsInternetAvalaible { get; }
        /// <summary>
        /// Gets/Sets the DogbreedsLetterA_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.DogbreedsLetterASchema> DogbreedsLetterA_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the DogbreedsLetterA_ListListControlCollectionPageNumber property.
        /// </summary>
		int DogbreedsLetterA_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedDogbreedsLetterA_ListListControlCollection property.
        /// </summary>
		Entities.DogbreedsLetterASchema SelectedDogbreedsLetterA_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the DogbreedsLetterB_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.DogbreedsLetterBSchema> DogbreedsLetterB_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the DogbreedsLetterB_ListListControlCollectionPageNumber property.
        /// </summary>
		int DogbreedsLetterB_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedDogbreedsLetterB_ListListControlCollection property.
        /// </summary>
		Entities.DogbreedsLetterBSchema SelectedDogbreedsLetterB_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the DogbreedsLetterC_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.DogbreedsLetterCSchema> DogbreedsLetterC_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the DogbreedsLetterC_ListListControlCollectionPageNumber property.
        /// </summary>
		int DogbreedsLetterC_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedDogbreedsLetterC_ListListControlCollection property.
        /// </summary>
		Entities.DogbreedsLetterCSchema SelectedDogbreedsLetterC_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the DogbreedsLetterD_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.DogbreedsLetterDSchema> DogbreedsLetterD_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the DogbreedsLetterD_ListListControlCollectionPageNumber property.
        /// </summary>
		int DogbreedsLetterD_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedDogbreedsLetterD_ListListControlCollection property.
        /// </summary>
		Entities.DogbreedsLetterDSchema SelectedDogbreedsLetterD_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the DogbreedsLetterE_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.DogbreedsLetterESchema> DogbreedsLetterE_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the DogbreedsLetterE_ListListControlCollectionPageNumber property.
        /// </summary>
		int DogbreedsLetterE_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedDogbreedsLetterE_ListListControlCollection property.
        /// </summary>
		Entities.DogbreedsLetterESchema SelectedDogbreedsLetterE_ListListControlCollection { get; set; }
        
        /// <summary>
        /// Gets the GetDogbreedsLetterA_ListListControlCollectionCommand command.
        /// </summary>
		ICommand GetDogbreedsLetterA_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetDogbreedsLetterB_ListListControlCollectionCommand command.
        /// </summary>
		ICommand GetDogbreedsLetterB_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetDogbreedsLetterC_ListListControlCollectionCommand command.
        /// </summary>
		ICommand GetDogbreedsLetterC_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetDogbreedsLetterD_ListListControlCollectionCommand command.
        /// </summary>
		ICommand GetDogbreedsLetterD_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetDogbreedsLetterE_ListListControlCollectionCommand command.
        /// </summary>
		ICommand GetDogbreedsLetterE_ListListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

        
        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
		ICommand AboutCommand { get; }

	}
}
