// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// DogbreedsLetterC_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IDogbreedsLetterC_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentDogbreedsLetterCSchema property.
        /// </summary>
		Entities.DogbreedsLetterCSchema CurrentDogbreedsLetterCSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaDogbreedsLetterC_Detail0 property.
        /// </summary>
		bool HasNextpanoramaDogbreedsLetterC_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaDogbreedsLetterC_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaDogbreedsLetterC_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechDogbreedsLetterC_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechDogbreedsLetterC_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareDogbreedsLetterC_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareDogbreedsLetterC_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartDogbreedsLetterC_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartDogbreedsLetterC_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaDogbreedsLetterC_Detail0 command.
        /// </summary>
		ICommand NextpanoramaDogbreedsLetterC_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaDogbreedsLetterC_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaDogbreedsLetterC_Detail0 { get; }

	}
}
