// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IDataSource.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// DogbreedsLetterA_DogbreedsLetterA interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IDogbreedsLetterA_DogbreedsLetterA
    {
		ObservableCollection<Entities.DogbreedsLetterASchema> GetData(int pageNumber = 0);
		ObservableCollection<Entities.DogbreedsLetterASchema> Search(FilterSpecification filter);
		bool HasPrevious(Entities.DogbreedsLetterASchema current);
		bool HasNext(Entities.DogbreedsLetterASchema current);
		Entities.DogbreedsLetterASchema Previous(Entities.DogbreedsLetterASchema current);
		Entities.DogbreedsLetterASchema Next(Entities.DogbreedsLetterASchema current);
    }
}
