// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IDataSource.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// DogbreedsLetterB_DogbreedsLetterB interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IDogbreedsLetterB_DogbreedsLetterB
    {
		ObservableCollection<Entities.DogbreedsLetterBSchema> GetData(int pageNumber = 0);
		ObservableCollection<Entities.DogbreedsLetterBSchema> Search(FilterSpecification filter);
		bool HasPrevious(Entities.DogbreedsLetterBSchema current);
		bool HasNext(Entities.DogbreedsLetterBSchema current);
		Entities.DogbreedsLetterBSchema Previous(Entities.DogbreedsLetterBSchema current);
		Entities.DogbreedsLetterBSchema Next(Entities.DogbreedsLetterBSchema current);
    }
}
