// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IDataSource.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// DogbreedsLetterD_DogbreedsLetterD interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IDogbreedsLetterD_DogbreedsLetterD
    {
		ObservableCollection<Entities.DogbreedsLetterDSchema> GetData(int pageNumber = 0);
		ObservableCollection<Entities.DogbreedsLetterDSchema> Search(FilterSpecification filter);
		bool HasPrevious(Entities.DogbreedsLetterDSchema current);
		bool HasNext(Entities.DogbreedsLetterDSchema current);
		Entities.DogbreedsLetterDSchema Previous(Entities.DogbreedsLetterDSchema current);
		Entities.DogbreedsLetterDSchema Next(Entities.DogbreedsLetterDSchema current);
    }
}
