// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// DogbreedsLetterD_DogbreedsLetterD data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class DogbreedsLetterD_DogbreedsLetterD : IDogbreedsLetterD_DogbreedsLetterD 
    {
		private const int MaxResults = 10;
        private readonly ObservableCollection<Entities.DogbreedsLetterDSchema> _data = new ObservableCollection<Entities.DogbreedsLetterDSchema>
		{
          new Entities.DogbreedsLetterDSchema
            {
                Id= new Guid("30279d4c-bf79-427a-ab0f-4ca6f48a9bee"),
                Title=@"Dachshund",
                Subtitle=@"ดัชชุนทั่วไปเป็นเวลานานฉกรรจ์และกล้ามเนื้อสั้นขาตอไม้ อุ้งเท้าด้านหน้ามันจะผิดปกติขนาดใหญ่และพายรูปสำหรับการขุดมาก Dachshunds เคลือบยาวมีขนอ่อนนุ่มและ featherings สั้นบนขาและหู มันมีผิวที่หลวมพอที่จะไม่ฉีกขาดในขณะที่การขุดอุโมงค์อยู่ในโพรงแน่นที่จะไล่ล่าเหยื่อ ดัชชุนมีหน้าอกลึกที่ให้ความจุปอดที่เพิ่มขึ้นสำหรับความแข็งแกร่งเมื่อการล่าสัตว์ใต้ดินเหยื่อ ของ จมูก ยาวด้วยพื้นที่ที่เพิ่มขึ้นจมูกที่ดูดซับกลิ่นไม่พึงประสงค์",
                Image=@"\Images\Item-1cef1c69-9999-4b13-82f9-a28e7083af66.jpg",
                Description=@"นักเขียนบางคนและผู้เชี่ยวชาญดัชชุน [51] มีมหาเศรษฐีที่รากต้นของดัชชุนกลับไป อียิปต์โบราณ ที่สลักถูกสร้างขึ้นมาที่มีการล่าสัตว์สุนัขสั้นขา [52] การค้นพบล่าสุดโดย มหาวิทยาลัยอเมริกันในกรุงไคโร ของ ตายซาก เหมือนดัชชุน สุนัขจากโกศศพโบราณของอียิปต์อาจให้ยืมความน่าเชื่อถือของทฤษฎีนี้ ในชาติที่ทันสมัยดัชชุนคือการสร้างเยอรมัน พ่อพันธุ์แม่พันธุ์ และรวมถึงองค์ประกอบของ เยอรมัน , ฝรั่งเศส และ อังกฤษ สุนัขและ สุนัข . Dachshunds ได้รับการเก็บรักษาไว้โดยศาลพระราชทั่วยุโรปรวมทั้ง สมเด็จพระราชินีวิกตอเรีย ซึ่งเป็นโดยเฉพาะอย่างยิ่งติดใจของสายพันธุ์ [53] พวกเขาได้รับการอบรมมาเพื่อล่าตัวแบดเจอร์โดยลากกลิ่น
ตรวจสอบการอ้างอิงแรกที่ดัชชุน แต่เดิมชื่อ ""Dachs Kriecher"" (""แบดเจอร์ซอฟต์แวร์รวบรวมข้อมูล"") หรือ ""Dachs Krieger"" (""แบดเจอร์นักรบ"") มาจากหนังสือที่เขียนในช่วงศตวรรษที่ 18 [54] ก่อนที่ มีอยู่การอ้างอิงถึง ""แบดเจอร์สุนัข"" และ ""หลุมสุนัข"" แต่เหล่านี้น่าจะหมายถึงวัตถุประสงค์มากกว่าสายพันธุ์ที่เฉพาะเจาะจง Dachshunds เยอรมันเดิมมีขนาดใหญ่กว่าความหลากหลายขนาดใหญ่ที่ทันสมัย​​และชั่งน้ำหนักระหว่าง 30 และ 40 ปอนด์ (14 และ 18 กก. ) และเดิมมาอยู่ในสายพันธุ์ตรงขาและงอขา (ดัชชุนทันสมัย​​สืบเชื้อสายมาจากหลัง) แต่สายพันธุ์ที่มีชื่อเสียงสำหรับการใช้งานในการทำลายล้างตัวแบดเจอร์และ แบดเจอร์-baiting , Dachshunds ก็ยังใช้กันทั่วไปสำหรับ กระต่าย และ สุนัขจิ้งจอก การล่าสัตว์สำหรับตำแหน่งที่ได้รับบาดเจ็บ กวาง และในแพ็คเป็นที่รู้จักกันในการล่าเกมเป็นใหญ่เป็น หมูป่า และรุนแรงเป็น Wolverine",
			},
          new Entities.DogbreedsLetterDSchema
            {
                Id= new Guid("96cd28e1-0195-43df-8d4d-755bf296e6fe"),
                Title=@"Dalmatian",
                Subtitle=@"ดัลเมเชี่ยนเป็นขนาดกลาง, ดีที่กำหนดสุนัขที่ดีของกล้ามเนื้อด้วย ความอดทน และความแข็งแกร่ง เมื่อเติบโตขึ้นอย่างเต็มรูปแบบ, น้ำหนักของมันตามปกติในช่วงระหว่าง 35 และ 70 ปอนด์ (16 และ 32 กก. ) และมันยืน 19-24 นิ้ว (48-61 เซนติเมตร) สูงกับเพศชายมักมีขนาดใหญ่กว่าตัวเมียเล็กน้อย [1] ร่างกายเป็น ยาวจาก forechest ก้นเป็นความสูงที่ไหล่และไหล่จะวางกลับ ฟุตดัลเมเชี่ยนที่อยู่รอบด้วยเท้าดีโค้งและเล็บมักจะมีสีขาวหรือสีเดียวกับจุดของสุนัข หูบางเรียวไปทางปลายและมีการตั้งค่าที่ค่อนข้างสูงและอยู่ใกล้กับหัว",
                Image=@"\Images\Item-f8dccb33-bf92-4b7e-805e-8543cd076e99.jpg",
                Description=@"FCI ได้รับการยอมรับ โครเอเชีย เป็นประเทศต้นกำเนิดของการอ้างแหล่งข่าวทางประวัติศาสตร์หลาย 
ภาพประกอบแรกของสุนัขที่ถูกพบในโครเอเชียภาพวาดแท่นบูชาใน Veli Lošinj นัดหมายกับ 1600-1630 และปูนเปียกใน Zaostrog .  รายละเอียดเอกสารแรกของดัลเมเชี่ยน ( โครเอเชีย : ปา Dalmatinski, Dalmatiner) ตรวจสอบย้อนกลับ ศตวรรษที่ 18 ต้นและที่เก็บของ อัครสังฆมณฑลของ Dakovo บน ที่สุนัขได้รับการกล่าวถึงและอธิบายว่าหมาป่า Dalmaticus ในพงศาวดารจากคริสตจักร 1719 โดยบาทหลวงพีต้าBakićแล้วอีกครั้งโดยพงศาวดารของคริสตจักรใน Andreas Keczkeméty 1739  ใน 1771 , โทมัสชายธง อธิบายสายพันธุ์ในหนังสือของเขาเรื่องย่อของสิงโตทะเลเขียนว่าต้นกำเนิดของสายพันธุ์มาจาก ดัล เขาเรียกมันว่าดัลเมเชี่ยน  หนังสือโดย โทมัส Bewick ประวัติทั่วไปของสิงโตทะเลที่ตีพิมพ์ในปี 1790 หมายถึง พันธุ์ดัลเมเชี่ยนเป็นโค้ชหรือสุนัข 
สายพันธุ์ที่ได้รับการพัฒนาและปลูกส่วนใหญ่ในประเทศอังกฤษ. [ อ้างจำเป็น ] มาตรฐานไม่เป็นทางการครั้งแรกสำหรับสายพันธุ์ที่ถูกนำโดยอังกฤษเวโรบีชอว์ในปี ค.ศ. 1882  ใน 1890 ที่มีการก่อตัวของดัลเมเชี่ยนคลับเป็นครั้งแรกในประเทศอังกฤษกลายเป็นมาตรฐาน อย่างเป็นทางการ  เมื่อสุนัขที่มีเครื่องหมายที่โดดเด่นก็แสดงให้เห็นเป็นครั้งแรกในประเทศอังกฤษในปี 1862 มันก็บอกว่าจะถูกใช้เป็นสุนัขเฝ้ายามและเพื่อนที่จะเร่ร่อนของดัล เสื้อโค้ทที่ไม่ซ้ำกันของพันธุ์กลายเป็นที่นิยมและแพร่หลายกระจายทั่วทวีปยุโรปเริ่มต้นในปี 1920 เครื่องหมายที่ผิดปกติของมันถูกกล่าวถึงบ่อยครั้งโดยนักเขียนเก่าที่ cynology",
			},
          new Entities.DogbreedsLetterDSchema
            {
                Id= new Guid("cd8659c6-8219-4723-a5e1-f32bb1254206"),
                Title=@"Dandie Dinmont Terrier",
                Subtitle=@"สายพันธุ์ที่มีขาสั้นที่มีความยาวลำตัว ผิดปกติในหมู่สายพันธุ์เทอร์เรีสก๊อตก็มีหูห้อย [23] คอเป็นกล้ามเนื้อมีการพัฒนาจากการใช้สายพันธุ์ที่มีขนาดใหญ่กับเกม [24] ความสูงทั่วไปที่ วิเธอร์ส เป็น 8-11 นิ้ว (20-28 เซนติเมตร) และพวกเขาสามารถชั่งน้ำหนักที่ใดก็ได้ระหว่าง 18-24 ปอนด์ (8.2-11 กก. ) [23] ในขณะที่ Dandie โดยทั่วไปเป็นสายพันธุ์ที่บึกบึนก็อาจมีปัญหาปีนบันได [23] พวกเขามีขนอ่อนนุ่มซึ่งรูปแบบ ""โมลี"" ด้านบนของหัวสุนัข [24] Dandie Dinmont Terrier มีรูปร่างคล้ายกับ สกายเทอร์เรี",
                Image=@"\Images\Item-734c4a6f-770e-4a02-8eda-ced5b0ee2f00.jpg",
                Description=@"สายพันธุ์มาจากสุนัขที่มีการใช้ใน ประเทศที่ชายแดน ของ สกอตแลนด์ และ อังกฤษ . 1600s ในช่วงที่พวกเขาถูกนำมาใช้สำหรับการล่าสัตว์ แบ๊ดเจ้อ และ นาก .  ในขณะที่ต้นกำเนิดของพวกเขาที่ดีที่สุดยังไม่ทราบเจ้าของสุนัข Allans ของ Holystone, นอร์ ธ ใน 1700s ต้นมีความคิดที่ได้รับการมีส่วนร่วมในต้นกำเนิดของพวกเขา  สุนัขเหล่านี้อาจได้รับชนิดของ ชายแดน Terrier ,  แม้ว่าทฤษฎีอื่น ๆ ที่มีอยู่รวมถึงความคิดที่ว่าพวกเขาจะข้ามระหว่าง สกอตแลนด์สุนัข และ สกายเทเรีย .  หัวหน้าครอบครัวนี้มีวิลลี่ ""ไพเพอร์"" อัลเลน ที่เกิดอยู่ใกล้ เบลลิงแฮม . เขาเป็น ชาวประมงบิน และสนุกกับการเล่นกีฬาของเขาและเก็บไว้ในสุนัขโดยเฉพาะอย่างยิ่งสำหรับการล่าสัตว์ของนาก ได้  ลอร์ด Ravensworth เมื่อจ้างอัลเลนจะเอานากจากบ่อใน Eslington ค . ลอร์ด Ravensworth พยายามที่จะซื้ออย่างใดอย่างหนึ่งของสุนัขอัลเลนได้รับการสนับสนุนหลังจากที่เขาประสบความสำเร็จออกนากซึ่งอัลเลนปฏิเสธ ได้  วิลลี่ไพเพอร์เสียชีวิตที่ 18 กุมภาพันธ์ 1779 และสุนัขของเขาผ่านเข้าไปในความดูแลของลูกชายของเขาเจมส์  เจมส์ ในที่สุดลูกชายสืบทอดสุนัขและขายสุนัขที่ชื่อ ""เก่าพริกไทย"" นายฟรานซิสซอมเมอร์ที่มาจาก เมือง Yetholm ด้านสกอตของชายแดน เก่าพริกไทยสืบเชื้อสายมาจากหนึ่งในสุนัขที่ชื่นชอบวิลลี่อัลเลนที่เคยร่วมงานคฤหาสน์ของลอร์ด Ravensworth 
สายพันธุ์ที่ยังคงไม่เป็นที่รู้จักนอกของเส้นขอบจนกระทั่ง 1814 เมื่อเซอร์ วอลเตอร์สก็อต นิยายของ Guy เนอ รับการตีพิมพ์ เซอร์วอลเตอร์ได้ใช้เวลาอยู่ในพื้นที่ในขณะที่นายอำเภอ Selkirkshire และได้เรียนรู้ของความกล้าหาญของเหล่านี้ประเภทของสุนัขผู้เชี่ยวชาญสำหรับการทำงานทั้ง สุนัขจิ้งจอก และนาก เมื่อเขาเขียน Guy เนอเขารวมตัวโดยใช้ชื่อของ ""Dandie Dinmont"" ที่เป็นเจ้าของจำนวนของสุนัขที่ชื่อ ""พริกไทย"" และ ""มัสตาร์ด"" หลังจากที่สีของเสื้อของพวกเขา ตัวละคร Dinmont อยู่บนพื้นฐานของเกษตรกรในชีวิตจริงและเทอร์เรีเจ้าของนายเจมส์เดวิดสัน  ที่เกินไปใช้เงื่อนไขทั่วไปของพริกไทยและมัสตาร์ดสำหรับสุนัขของเขาขึ้นอยู่กับเสื้อ  สุนัขเดวิดสันมาจากความหลากหลายของ แหล่งรวมทั้งสุนัขของอัลลันเดอร์สันและครอบครัว Faas  เดวิดสันเอกสารการผสมพันธุ์ของเขาและได้รับการยอมรับว่าเป็นพ่อของสายพันธุ์ที่ทันสมัย",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of DogbreedsLetterDSchema items.
        /// </summary>
        /// <returns>An observable collection of DogbreedsLetterDSchema items.</returns>
        public ObservableCollection<Entities.DogbreedsLetterDSchema> GetData(int numPage)
        {								
			return new ObservableCollection<Entities.DogbreedsLetterDSchema>(_data.Skip(MaxResults * numPage).Take(MaxResults));
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of DogbreedsLetterDSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of DogbreedsLetterDSchema items.</returns>
        public ObservableCollection<Entities.DogbreedsLetterDSchema> Search(FilterSpecification filter)
        {
            return RepositoriesBase.Filter<Entities.DogbreedsLetterDSchema>.FilterCollection(filter, _data);
        }
		
		/// <summary>
        /// Checks if data source has a element before the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a previous element, false if there is not</returns>
		public bool HasPrevious(Entities.DogbreedsLetterDSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) > 0;
        }
		
		/// <summary>
        /// Checks if data source has a element after the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a next element, false if there is not</returns>
		public bool HasNext(Entities.DogbreedsLetterDSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) < _data.Count - 1;
        }
		
		/// <summary>
        /// Retrieves the previous element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The previous element from items, if it exists. Otherwise, returns null</returns>
        public Entities.DogbreedsLetterDSchema Previous(Entities.DogbreedsLetterDSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.First().Equals(current)) return null;

            return _data[_data.IndexOf(current) - 1];
        }
		
		/// <summary>
        /// Retrieves the next element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The next element from items, if it exists. Otherwise, returns null</returns>
        public Entities.DogbreedsLetterDSchema Next(Entities.DogbreedsLetterDSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.Last().Equals(current)) return null;

            return _data[_data.IndexOf(current) + 1];
        }
	}
}

