// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// DogbreedsLetterB_DogbreedsLetterB data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class DogbreedsLetterB_DogbreedsLetterB : IDogbreedsLetterB_DogbreedsLetterB 
    {
		private const int MaxResults = 10;
        private readonly ObservableCollection<Entities.DogbreedsLetterBSchema> _data = new ObservableCollection<Entities.DogbreedsLetterBSchema>
		{
          new Entities.DogbreedsLetterBSchema
            {
                Id= new Guid("ac81dc2f-b782-4787-b2a0-bd1709a76d98"),
                Title=@"Bakharwal Dog",
                Subtitle=@"Deep-chested, กล้ามเนื้อและเปรียวแคชเมียร์แกะมีหลังตรงไหล่กว้างและขายาว ร่างกายมีกระดูกอย่างยิ่งกับคอที่มีประสิทธิภาพและหัวขนาดใหญ่ เสื้อแบนขนาดกลางที่มีความยาวมากหนาและ undercoated หนาแน่นให้การป้องกันที่เหมาะสมจากสภาพภูมิอากาศที่รุนแรงของพื้นที่รวมทั้งจาก การล่า . ที่พบมากที่สุดและมีมูลค่า สี เป็นสีดำและสีน้ำตาล แต่บาง tricoloured และ หัวมังกุท้ายมังกร ตัวอย่างสามารถพบได้เช่นกัน ความหลากหลายของขนาดสามารถพบจากตัวอย่างที่มี 24 นิ้วสูงกับผู้เกิน 30 นิ้วที่ วิเธอร์",
                Image=@"\Images\Item-9772bb70-1e8e-402c-9ff3-595d9e98b496.jpg",
                Description=@"เป็นความหลากหลายของเอเชีย leaner Molossers , แกะแคชเมียร์เป็นที่เกี่ยวข้องกับการบางประเภท แมสทิฟทิเบต และสุนัขของ เอเชียกลาง แต่โดยอ้างว่าเป็นชายฉกรรจ์ Gujjar จะมากเก่ากว่าสายพันธุ์อื่น ๆ ในภูมิภาค ขณะนี้เป็นที่ถกเถียงกันสีดำและสีน้ำตาลและการสร้างทางกายภาพของ Bakarwal สุนัขพันธุ์หนึ่งได้นำเจ้าหน้าที่บางส่วนที่จะเชื่อมโยงจำนวนเก่า Molosser สุนัขนี้คือ Hyrcanian สุนัขพันธุ์หนึ่ง ที่ Molossos มอก. Epirou , ป่า , Tuvan แกะ และ Siah แซก หลากหลายของ อิหร่าน Mazandarani Sage เป็นลูกหลานของยุโรปสายพันธุ์เหล่านี้",
			},
          new Entities.DogbreedsLetterBSchema
            {
                Id= new Guid("4e3321de-efb7-40ec-94cc-482ca8e0f26a"),
                Title=@"Barbet",
                Subtitle=@"สายพันธุ์ยืน 58-65 เซนติเมตร (20.5-25.5 นิ้ว) สำหรับเพศชายในความสูง 52-61 (20.47-24.01 นิ้ว) สำหรับผู้หญิงที่มีความอดทน 1 ซม. + / - และน้ำหนัก 17-28 กิโลกรัม (35-60 ปอนด์) ปกเป็นต้นแบบ น้ำสุนัข ที่มีขนยาวและขนหยิก เสื้อโค้ทของพวกเขาเติบโตระยะยาวและต้องได้รับการดูแลเป็นอย่างดีอย่างสม่ำเสมอมิฉะนั้นเสื้อสามารถกลายเป็นสังกะตังและปกอาจสูญเสียกระจุกเล็ก ๆ ของผมเช่น tumbleweeds",
                Image=@"\Images\Item-2b5dc8f7-c98b-48ce-ba58-b3d22150d2d2.jpg",
                Description=@"สายพันธุ์ที่ปกเป็นส่วนหนึ่งของประวัติศาสตร์ของสุนัขและสายพันธุ์ที่คุ้นเคยหลายคนได้ปกในวงศ์ตระกูลของพวกเขา ทั้งนี้ขึ้นอยู่กับภูมิศาสตร์และความจำเป็นปกเชื่อมต่อผ่านหลายศตวรรษในความสามารถต่างๆและเป็นสุนัขสหาย แต่เป็นสุนัขทุกรอบการทำงาน ชื่อปกตลอดหลายศตวรรษกลายเป็นชื่อ ""ทั่วไป"" สุนัขมีความยาวหยิกเสื้อขน [2]
`แกรนด์ปก` ที่ปรากฎในหนังสือจำนวนจอร์จหลุยส์ตลกของ `Histoire Naturelle '(1750) เป็นความคิดที่เป็นแหล่งเดิมของสายพันธุ์สุนัขน้ำต่างๆ ( พุดเดิ้ล , โปรตุเกสน้ำสุนัข , อเมริกันน้ำสแปเนียล , และอื่น ๆ ) ต้นกำเนิดที่แท้จริงของมันจะหายไปในสมัย​​โบราณ แต่อาจเกิดจากการลงทุนในทิศทางเดียวกันหุ้นแบบมีสาย
ปกเป็นสุนัขน้ำฝรั่งเศสและชื่อของพันธุ์ ""ปก"" มาจากคำภาษาฝรั่งเศส barbe ซึ่งหมายความว่าเครา ปกยังทำงานเป็นผู้ช่วยของทหารเรือเหมือนน้ำสุนัขโปรตุเกส มันเป็นที่รู้จักดีที่สุดสำหรับการเป็นสุนัขจำพวกนกน้ำในบึงชายเลนและปากแม่น้ำของฝรั่งเศส [3] ซึ่งเป็นที่ที่การแสดงออก ""เต็มไปด้วยโคลนเป็นปก"" มาจากศตวรรษที่ 19 ระหว่างวันที่ 18 ถึงปลายศตวรรษที่ 19 สุนัขเดียวกันเป็นที่รู้จักปกในฝรั่งเศส barbone ในอิตาลีและในประเทศเยอรมนี pudel; เกือบร้อยปีที่ ปกและพุดเดิ้ล ถูกถือเป็นหนึ่งเดียวกัน กับการถือกำเนิดของการแสดงสุนัขและคัดเลือกพันธุ์ตามหมดจดในความงามพุดเดิ้ลได้รับการพัฒนาให้เป็นที่สง่างามมากขึ้นและมีสีทึบจะแตกต่างจากที่ผ่านมาที่พบบ่อยมากขึ้น ธรรมชาติที่หลากหลายของปกมีความหมายอยู่รอดของตนและหลายวันนี้ปกยังคงมีสินทรัพย์ประกอบกับพวกเขาจากอดีตที่ผ่านมาและต้นกำเนิดปกและนํ้าสามารถตรวจสอบกลับไปยังการเขียนมาตรฐานแรกใน 1891",
			},
          new Entities.DogbreedsLetterBSchema
            {
                Id= new Guid("a3860404-f45a-4126-984a-d704ea46f444"),
                Title=@"Basenji",
                Subtitle=@"Basenjis มีสุนัขผมสั้นขนาดเล็กสง่างามที่มองกับหูตั้งตรงหางขดแน่นและคอที่สง่างาม หน้าผาก basenji ที่เป็นรอยย่นมากขึ้นดังนั้นเมื่อพวกเขาเป็นหนุ่มสาวหรือหนุ่มมาก ตา basenji ของอัลมอนด์มักจะมีรูปซึ่งมักจะให้สุนัขลักษณะของ squinting Basenjis มักจะมีน้ำหนักประมาณ 24 ปอนด์และยืน 16 นิ้วที่ไ​​หล่ พวกเขาเป็นสายพันธุ์ที่ตารางซึ่งหมายความว่าพวกเขาตราบเท่าที่พวกเขาจะสูง Basenjis เป็นสุนัขแข็งแรงและเป็นจริงที่มีประสิทธิภาพ deceptively สำหรับขนาดของพวกเขา พวกเขามีความสง่างามเดินมั่นใจเหมือนม้าวิ่งเหยาะ",
                Image=@"\Images\Item-639c5753-9d5d-4ad8-bd45-e538f1abd9d6.jpg",
                Description=@"Basenji เป็น arguably มากที่สุด สุนัขสายพันธุ์โบราณ นั่นคือจะบอกว่าบรรพบุรุษร่วมหุ้นกับสุนัขทั้งหมดที่มีอยู่อื่น ๆ ที่อาศัยอยู่อีกต่อไปที่ผ่านมากว่าบรรพบุรุษของสุนัขสองตัวที่อยู่อาศัยอื่น ๆ [13] แต่นี้ไม่ได้บอกว่า บรรพบุรุษร่วมกันมากที่สุดโบราณของสุนัขทั้งหมดเป็น Basenji เป็นลักษณะที่กำหนดสายพันธุ์อาจมีการพัฒนาตั้งแต่นั้นมา แม้ว่า Basenji ทันสมัยจากกลางแอฟริกาในบางจุดนานมาแล้วบรรพบุรุษของตนมาถึงที่นั่นมาจากเอเชียตะวันออกที่มีวิวัฒนาการมาจากหมาป่าทั้งจีนหรือเอเชียตะวันออกเฉียงใต้ [14]
ที่มีต้นกำเนิดในทวีป แอฟริกา , [15] สุนัข basenji เหมือนมีชีวิตอยู่กับมนุษย์เป็นพัน ๆ ปี สุนัขคล้าย Basenjis ทันสมัยสามารถเห็นได้บน stelae ในสุสานของ อียิปต์ ฟาโรห์ นั่งอยู่ที่เท้าของโทของพวกเขาที่กำลังมองหาเช่นเดียวกับที่พวกเขาทำในวันนี้กับหู pricked และหางขดแน่น สุนัขชนิดนี้ถูกเก็บไว้เดิมสำหรับการล่าสัตว์เกมขนาดเล็กโดยการติดตามและการขับรถเกมในข่าย, [16] [17]
ยุโรปครั้งแรกที่อธิบายชนิดของสุนัขที่พันธุ์ Basenji ได้มาใน ประเทศคองโก ในปี 1895 สุนัขเหล่านี้ในท้องถิ่นซึ่งชาวยุโรประบุว่าเป็นสายพันธุ์ที่ไม่ซ้ำกันและเรียกว่า ""basenji"" ได้รับรางวัลโดยชาวบ้านของพวกเขาฉลาด, ความกล้าหาญ, ความเร็ว, และความเงียบ บทความที่ตีพิมพ์ที่เรียกว่าหน่วยสืบราชการลับของสุนัขโดยสแตนเลย์ Coren, Ph.D. คำถามนี้ ได้จัดอันดับสายพันธุ์ที่ # 78 จาก 79 ซึ่งเป็นครั้งที่สองไปที่ระดับต่ำสุดในหน่วยสืบราชการลับ นี้ได้รับการพิจารณาโดยบางที่จะเป็นรายการที่ไม่น่าเชื่อถือเป็นเพียงมุ่งเน้นไปที่ความสามารถในการฟังคำสั่งแรก สุนัขที่เป็นอิสระเช่น Basenjis และอัฟกานิสถาน Hounds ได้รับการพิจารณาโดยบางส่วนจะฉลาดกว่าสายพันธุ์เชื่อฟังเพราะความสามารถในการรับรู้สิ่งที่เป็นประโยชน์ต่อพวกเขาและสิ่งที่เป็นเพียงเพื่อโปรดอีก [18]
Basenjis เป็นผู้ช่วยในการล่าไล่สัตว์ป่าในข่ายสำหรับโทของพวกเขา azande และ Mangbetu ผู้คนจากภาคตะวันออกเฉียงเหนือของคองโกอธิบาย basenjis ในท้องถิ่น ภาษาลิง เป็น MBWA na basɛnzi แปลนี้หมายถึง ""สุนัขป่า"" หรือ ""สุนัขของชาวบ้าน"" ในคองโก basenji เป็นที่รู้จักกันในฐานะ ""สุนัขจากพุ่มไม้."" สุนัขนอกจากนี้ยังเป็นที่รู้จักกัน azande ทางใต้ของซูดานเป็น Ango Angari [19] basɛnziคำตัวเองเป็นรูปพหูพจน์ของmosɛnzi ใน ภาษาสวาฮิลี อีก ภาษาเป่า จากแอฟริกาตะวันออก mbwa shenzi แปลว่า ""สุนั",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of DogbreedsLetterBSchema items.
        /// </summary>
        /// <returns>An observable collection of DogbreedsLetterBSchema items.</returns>
        public ObservableCollection<Entities.DogbreedsLetterBSchema> GetData(int numPage)
        {								
			return new ObservableCollection<Entities.DogbreedsLetterBSchema>(_data.Skip(MaxResults * numPage).Take(MaxResults));
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of DogbreedsLetterBSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of DogbreedsLetterBSchema items.</returns>
        public ObservableCollection<Entities.DogbreedsLetterBSchema> Search(FilterSpecification filter)
        {
            return RepositoriesBase.Filter<Entities.DogbreedsLetterBSchema>.FilterCollection(filter, _data);
        }
		
		/// <summary>
        /// Checks if data source has a element before the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a previous element, false if there is not</returns>
		public bool HasPrevious(Entities.DogbreedsLetterBSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) > 0;
        }
		
		/// <summary>
        /// Checks if data source has a element after the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a next element, false if there is not</returns>
		public bool HasNext(Entities.DogbreedsLetterBSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) < _data.Count - 1;
        }
		
		/// <summary>
        /// Retrieves the previous element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The previous element from items, if it exists. Otherwise, returns null</returns>
        public Entities.DogbreedsLetterBSchema Previous(Entities.DogbreedsLetterBSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.First().Equals(current)) return null;

            return _data[_data.IndexOf(current) - 1];
        }
		
		/// <summary>
        /// Retrieves the next element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The next element from items, if it exists. Otherwise, returns null</returns>
        public Entities.DogbreedsLetterBSchema Next(Entities.DogbreedsLetterBSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.Last().Equals(current)) return null;

            return _data[_data.IndexOf(current) + 1];
        }
	}
}

