// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// DogbreedsLetterA_DogbreedsLetterA data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class DogbreedsLetterA_DogbreedsLetterA : IDogbreedsLetterA_DogbreedsLetterA 
    {
		private const int MaxResults = 10;
        private readonly ObservableCollection<Entities.DogbreedsLetterASchema> _data = new ObservableCollection<Entities.DogbreedsLetterASchema>
		{
          new Entities.DogbreedsLetterASchema
            {
                Id= new Guid("b5861b03-574f-4f04-88e0-35aa274a85b5"),
                Title=@"Affenpinscher",
                Subtitle=@"Affenpinscher เป็นสุนัขขนาดเล็กที่มีขนดก, แกร่งประเภทเสื้อ ผมบนใบหน้ามีความยาวกว่าส่วนที่เหลือของร่างกายให้มันดูแตกต่างกัน มันเป็นรุ่นเล็กของเทอร์เรีทำงานและไม่ได้เป็นสุนัขที่ละเอียดอ่อน แต่ก็มีร่างกายเมตรโดยมีวงกว้างปานกลางหน้าอกลึก หัวกลมที่มีการหยุดเด่นชัดซึ่งเป็นพื้นที่การเปลี่ยนผ่านจาก backskull ที่ปากกระบอกปืน ขากรรไกรล่างเป็น undershot และกว้างพอสำหรับฟันล่างถูกตรงและแม้แต่ยื่นออกมาด้านล่างของสุนัขจมูกสั้น โดดเด่นดวงตากลมมีสีดำ คอสั้นและโค้งและแขนขาจะตรงและกระดูกดี",
                Image=@"\Images\Item-a0539cd8-1bd3-40b4-919f-da8fc1d19029.JPG",
                Description=@"ไม่มีข้อมูลที่แน่นอนเกี่ยวกับต้นกำเนิดของ Affenpinscher มีอยู่ แต่ก็เป็นหนึ่งในที่เก่าแก่ที่สุดในสายพันธุ์ของเล่น มันเป็นเรื่องที่เกี่ยวข้องอย่างแน่นอนเพื่อ บรัสเซลส์แร้ง และอาจจะเทอร์เรี มันเป็นชื่อ ""ลิงหมา"" เพราะลิงเหมือนโครงสร้างใบหน้าและการแสดงออกของ มันเป็นความเชื่อที่ Affenpinscher เกิดขึ้นในเยอรมนีและ Affenpinscher ชื่อแปลจากภาษาเยอรมันคือ ""ลิง Terrier."" มีความเชื่อกันว่า Affenpinschers แรกเป็นขนาดใหญ่ที่พวกเขาสุนัขฟาร์มที่ทำงานเป็น ratters Affenpinscher ได้รับการขนาดเล็กและกลายเป็นสัตว์เลี้ยงที่บ้านในช่วงศตวรรษที่ 18 และ 19 มันก็ยังคงเป็นนักล่าที่ไร้ความปรานีของหนูและสุนัขเฝ้าบ้านที่โดดเด่น วันนี้ Affenpinscher เป็นหลักสุนัขคู่หู Affenpinscher เป็นที่ยอมรับในหนังสือบันทึกอเมริกันสุนัขของสโมสรในปี 1936",
			},
          new Entities.DogbreedsLetterASchema
            {
                Id= new Guid("409549ef-864f-42a0-86f6-160c74ae9fcb"),
                Title=@"Afghan Hound",
                Subtitle=@" อัฟกาน ฮาวน์ เป็นสุนัขที่มีความสง่างาม ดูแล้วเป็นสุนัขที่มีความคลาสสิคมากในตัว เมื่อมองจากด้านหน้าจะดูตรงหัวเชิด ตรงคอยาวโค้งได้สัดส่วน ขนยาว ท่วงท่าในการเคลื่อนไหวจะต้องสง่าวามให้สมกับที่ฝรั่งเขาตั้งให้ว่าเป็น THE KING OF DOG",
                Image=@"\Images\Item-da6d239b-5833-4b9f-82d8-37ae8af6dafc.jpg",
                Description=@"จากประเทศที่เขาทำให้ได้ชื่อนี้มาอัฟกัน ฮาวนด์ เป็นสุนัขประจำชาติถึงแม้ว่าจะไม่เป็นทางการก็ตาม ชนพื้นเมืองอัฟกัน เชื่อว่าสุนัขพันธุ์นี้คือสุนัขในภาพวาดบนผนังถ้ำในตอนเหนือของประเทศ แคว้นบัคก์ ซึ่งก็เป็นสาเหตุที่ทำให้สุนัขพันธุ์อัฟกัน ฮาวนด์ มีอีกชื่อหนึ่งว่า บัลก์ฮาวนด์ พวกเขาเป็นนักล่าด้วยสายตามากกว่าการดมกลิ่น เนื่องจากมีสายตาที่ฉับไวเป็นเลิศ และมีความว่องไวซึ่งเป็นสิ่ง สำคัญในการไล่ล่าเหยื่อขนที่หนาฟูปกป้องพวกเขาจากอากาศหนาวจัดในบริเวณตอนเหนือที่มีหิมะตก และในขณะเดียวกันก็ป้องกันพวกเขาจากแสงแดดที่รุนแรงของทะเลทรายอุ้งเท้าที่หนาและใหญ่ และขาหลังที่แข็งแรง ทำให้พวกเขาสามารถเดินทางข้ามทะเลทราย ร้อนจัดหรือบนเขาขรุขระได้",
			},
          new Entities.DogbreedsLetterASchema
            {
                Id= new Guid("3faf507b-39d1-43f8-b7aa-224e62d09b28"),
                Title=@"Aidi",
                Subtitle=@"ยืน 20 ถึง 25 นิ้ว (51-64 เซนติเมตร) ความสูงและน้ำหนักประมาณ£ 55 (25 กก. ), ยันร่างกายกล้ามเนื้อ Aidi ถูกป้องกันโดยหยาบหนาเสื้อทนทุกสภาพอากาศมีหางขนนกหนัก เสื้อโค้ทหนักและนุ่มน่าแปลกใจสำหรับสายพันธุ์แอฟริกัน หัวเป็น หมี เหมือนและในสัดส่วนที่เหลือของร่างกาย สายพันธุ์ที่มีเรียว ปากกระบอกปืน ที่มีจมูกสีดำหรือสีน้ำตาลที่มักจะตรงกับเสื้อโค้ท ขากรรไกรของพวกเขามีความแข็งแรงด้วยริมฝีปากสีดำหรือสีน้ำตาลแน่น หูขนาดกลางจะเอียงไปข้างหน้าและลดลงเล็กน้อย ตามีขนาดกลางที่มีสีเข้มและขอบสีดำ เสื้อ สีที่มีสีขาว",
                Image=@"\Images\Item-7e6c3313-f07e-43de-8a54-8a595e168a09.jpg",
                Description=@"Aidi (สุนัขอาหรับในตูนิเซีย) ได้รับการยอมรับว่ามาจากแอฟริกาเหนือ (แอลจีเรียตูนิเซียลิเบียและ Marroco อาจจะเกิดขึ้นใน ทะเลทรายซาฮาร่า สุนัขไม่เคยทำงานเป็น. สุนัขชีพด็อก ถึงแม้ปี 1963 มาตรฐานที่ถูกตีพิมพ์ภายใต้ชื่อ Atlas แกะนี้ ได้รับการแก้ไขในปี 1969. สุนัขที่กล้าหาญ, Aidi อาศัยและทำงานอยู่ใน เทือกเขาแอตลาส ของโมร็อกโก, ลิเบีย และ แอลจีเรีย ปกป้องเจ้าของและทรัพย์สินของเขาจากปักล่าอื่น ๆ และคนแปลกหน้า [2] สายพันธุ์นี้ได้รับการเรียกว่าเบอร์เบอร์ หลังจากที่ เบอ เผ่าที่ใช้มันและมีความคล้ายคลึงบางอย่างเพื่อให้ สุนัขจัณฑาล ซึ่งเชื่อว่าจะมีส่วนร่วมและวงศ์ตระกูลของตน. ในฐานะที่เป็นผู้พิทักษ์แห่งทะเลทรายชนเผ่าเร่ร่อนที่สุนัขตื่นตัวมากที่สุดและได้รับการก้าวร้าวเดิมพันรอบปริมณฑลของค่ายในเวลากลางคืน . Aidi ยังไม่ได้รับการยกย่องอย่างสูงจากชนเผ่าในอดีตเช่นเดียวกับสุนัขอื่น ๆ ส่วนใหญ่กว่า Sloughi และสายพันธุ์อื่น ๆ ถือได้ว่าเป็นเกียรติ. แต่โมร็อกโกได้เกิดเมื่อเร็ว ๆ นี้สโมสรที่จะปกป้องความบริสุทธิ์ของสายพันธุ์ที่ได้มีส่วนร่วมมากในการให้ หลายบทบาทเป็นผู้พิทักษ์นักล่าสุนัขตำรวจและสัตว์เลี้ยง [3] แม้ว่า Aidi ได้รับการใช้งานเป็นหลักเป็นสุนัขทำงานเขาได้กลายเป็นเรื่องปกติมากขึ้นเป็นสุนัขบ้านในประเทศ. สายพันธุ์นี้ยังทำให้สัตว์เลี้ยงในเมืองที่ดี ถ้าเขาจะได้รับงานและการออกกำลังกายมากพอที่จะทำให้เขามีความพึงพอใจและมีความสุข",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of DogbreedsLetterASchema items.
        /// </summary>
        /// <returns>An observable collection of DogbreedsLetterASchema items.</returns>
        public ObservableCollection<Entities.DogbreedsLetterASchema> GetData(int numPage)
        {								
			return new ObservableCollection<Entities.DogbreedsLetterASchema>(_data.Skip(MaxResults * numPage).Take(MaxResults));
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of DogbreedsLetterASchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of DogbreedsLetterASchema items.</returns>
        public ObservableCollection<Entities.DogbreedsLetterASchema> Search(FilterSpecification filter)
        {
            return RepositoriesBase.Filter<Entities.DogbreedsLetterASchema>.FilterCollection(filter, _data);
        }
		
		/// <summary>
        /// Checks if data source has a element before the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a previous element, false if there is not</returns>
		public bool HasPrevious(Entities.DogbreedsLetterASchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) > 0;
        }
		
		/// <summary>
        /// Checks if data source has a element after the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a next element, false if there is not</returns>
		public bool HasNext(Entities.DogbreedsLetterASchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) < _data.Count - 1;
        }
		
		/// <summary>
        /// Retrieves the previous element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The previous element from items, if it exists. Otherwise, returns null</returns>
        public Entities.DogbreedsLetterASchema Previous(Entities.DogbreedsLetterASchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.First().Equals(current)) return null;

            return _data[_data.IndexOf(current) - 1];
        }
		
		/// <summary>
        /// Retrieves the next element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The next element from items, if it exists. Otherwise, returns null</returns>
        public Entities.DogbreedsLetterASchema Next(Entities.DogbreedsLetterASchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.Last().Equals(current)) return null;

            return _data[_data.IndexOf(current) + 1];
        }
	}
}

