// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// DogbreedsLetterE_DogbreedsLetterE data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class DogbreedsLetterE_DogbreedsLetterE : IDogbreedsLetterE_DogbreedsLetterE 
    {
		private const int MaxResults = 10;
        private readonly ObservableCollection<Entities.DogbreedsLetterESchema> _data = new ObservableCollection<Entities.DogbreedsLetterESchema>
		{
          new Entities.DogbreedsLetterESchema
            {
                Id= new Guid("75a5decb-3ef3-407c-bb60-d49da4dae56c"),
                Title=@"East Siberian Laika",
                Subtitle=@"เพศผู้มี 55-66 เซนติเมตร (22-26 ใน) ขณะที่ผู้หญิงอยู่ในด้านขนาดเล็กที่ 51 ถึง 60 เซนติเมตร (20-24 ใน) สีดำและสีน้ำตาลกับแพทช์ไฟ (เรียกว่า karamis) หงอก, ปะ, ticked, สีขาว, สีเทา, สีดำ, สีแดงและสีน้ำตาลของเฉดสีทั้งหมด มีสองประเภทหลักที่ Evenki และ Irkutsk ดังนี้ประเภทอื่น ๆ ที่สำคัญน้อยซาอามูร์และ Tofolar ประเภทนี้แตกต่างกันในสีและร่างกายเป็นภาษาอังกฤษยังคงเป็นสายพันธุ์มากขึ้นของกลุ่มที่มีความหลากหลายกว่าอีกสามรัสเซีย สายพันธุ์ส่วน . ร่างกาย ESL ค่อนข้างมีภูเขามากเกือบเมตรในสัดส่วนที่สูงกว่า",
                Image=@"\Images\Item-cc24bf58-e8cc-4aae-9cb1-eda5f54cae41.jpg",
                Description=@"การกำหนดสายพันธุ์ที่ได้รับการก่อตั้งขึ้นที่ ยูเนี่ยนทั้งหมด Cynological สภาคองเกรส ในปี 1947 พร้อมกับที่ของคนอื่นอีกสาม สายพันธุ์ส่วน . สายพันธุ์ที่เกิดขึ้นกับสุนัขจาก ทะเลสาบไบคาล ในภูมิภาค จังหวัด Irkutsk , Evenki มณฑล , แม่น้ำอามูร์ ลุ่มน้ำและ ดินแดนทางทะเล . มาตรฐานสายพันธุ์แรกที่ถูกกำหนดโดยนักชีววิทยาสัตว์ป่า KG Abramov . พันธุ์เป็นระบบเริ่มต้นขึ้นในปี 1970 ในสุนัขรัฐบาลที่ Irkutsk และ เลนินกราด ",
			},
          new Entities.DogbreedsLetterESchema
            {
                Id= new Guid("93f1eeff-98c9-4c90-99e6-a505e933cf30"),
                Title=@"East-European Shepherd",
                Subtitle=@"ยุโรปตะวันออกต้อนมีขนาดใหญ่กว่าสุนัขเฉลี่ย: เพศชายมี 26-28 นิ้วที่วิเธอร์สในขณะที่เพศหญิงมี 23-26 นิ้ว พร้อมกับเสื้อโค้ทสั้นขนหนาแน่นพวกเขามีกระดูกที่แข็งแรง (แต่ไม่หยาบ) และกล้ามเนื้อมีการพัฒนา เสื้อโค้ทของพวกเขาเป็นสื่อในระยะเวลาที่มีเสื้อทั้งการพัฒนา สีที่ได้รับการยอมรับสำหรับสุนัขเหล่านี้รวมถึงอาน (ที่สามารถอิ่มตัวเพื่อให้เกือบสีดำและสีน้ำตาลหรือลักษณะที่ปรากฏสีดำและสีแดง), ผ้าห่มกลับสีดำและสีน้ำตาล, สีดำ, และตับของแข็งของแข็ง บางสีที่หายาก ได้แก่ สีฟ้า (อาน, ผ้าห่มกลับและของแข็ง)",
                Image=@"\Images\Item-00592925-1239-4a78-9f3a-fa10ef0699e7.jpg",
                Description=@"ยุโรปตะวันออกต้อนมีขนาดใหญ่กว่าสุนัขเฉลี่ย: เพศชายมี 26-28 นิ้วที่วิเธอร์สในขณะที่เพศหญิงมี 23-26 นิ้ว พร้อมกับเสื้อโค้ทสั้นขนหนาแน่นพวกเขามีกระดูกที่แข็งแรง (แต่ไม่หยาบ) และกล้ามเนื้อมีการพัฒนา เสื้อโค้ทของพวกเขาเป็นสื่อในระยะเวลาที่มีเสื้อทั้งการพัฒนา สีที่ได้รับการยอมรับสำหรับสุนัขเหล่านี้รวมถึงอาน (ที่สามารถอิ่มตัวเพื่อให้เกือบสีดำและสีน้ำตาลหรือลักษณะที่ปรากฏสีดำและสีแดง), ผ้าห่มกลับสีดำและสีน้ำตาล, สีดำ, และตับของแข็งของแข็ง บางสีที่หายาก ได้แก่ สีฟ้า (อาน, ผ้าห่มกลับและของแข็ง), เงิน, และของแข็งสีขาว หนูบางชนิดสีเทาและสีแดงจะได้รับอนุญาตให้เพาะพันธุ์ แต่ไม่ต้องการ
หัวหน้าต้อนยุโรปตะวันออกเป็นของ 'สวาปาม' ลักษณะที่วางอยู่บนคอยาวในเฟอร์คอค่อนข้างใหญ่ก็เป็นสัดส่วนที่เหลือของร่างกาย มันเป็นรูปสามเหลี่ยมและรูปลิ่มกับหน้าผากโค้งมนเล็กน้อย ปากกระบอกปืนมีค่าเท่ากับความยาวถึงหัวกะโหลกและขากรรไกรล่างมีการพัฒนาที่ดี ที่มีฟันขนาดใหญ่ที่ซับซ้อนและมีประสิทธิภาพกล้ามเนื้อขากรรไกรเต็มสุนัขมีความสามารถในการถือที่แข็งแกร่งมากและกรรไกรตัดกัด หูของพวกเขาเป็นสื่อในขนาดและ pricked สายตาของพวกเขาเป็นสื่อรูปไข่, และดำที่มีการปิดกระชับเปลือกตาด้วยสี ยอมรับ [ โดยใคร? ] สีสำหรับการเพาะพันธุ์เป็นสีเหลืองอำพัน, สีน้ำตาลและสีน้ำตาลแดง
หลังของพวกเขามีความแข็งแรงกว้างและยาว เอวมีความยาวและกว้างทั้งกล้ามเนื้อและโค้งเล็กน้อย ซางของพวกเขาคือกว้างยาวและเอียงเล็กน้อยไปทางหาง หางจะยาวหมีเฟอร์หนาสร้างขึ้นในรูปแบบของดาบเมื่อตื่นเต้นของสุนัข หน้าอกกว้างปานกลางในขณะที่ท้องซุกขึ้นพอสมควร ทรวงอกเป็นดาบสั้นในรูปแบบถึงกระดูกหรืออีกเล็กน้อยในบางกรณี ขามีความแข็งแรงและตรงเท้าเป็นรูปไข่และมีขนาดกะทัดรัด ก้าวของสุนัขเป็นสัตว์ที่เหยาะย่างมากกว่าของการลื่นไถลเลื่อนเพียงแค่เหนือพื้นดินทั่วไปเพื่อให้ญาติของคนเลี้ยงแกะเยอรมันอื่น ๆ",
			},
          new Entities.DogbreedsLetterESchema
            {
                Id= new Guid("9d44a44d-695e-4bb1-b36d-bacb5e5bae17"),
                Title=@"Elo",
                Subtitle=@"อบรมพฤติกรรมมากกว่ามาตรฐานที่ปรากฏลักษณะของอีโลจะแตกต่างจากสุนัขกับสุนัขถึงแม้ว่า สายพันธุ์ มาตรฐาน (มาตรฐานสายพันธุ์อธิบายลักษณะภายนอกของพันธุ์) อธิบายขนาด 46-60 ซม. ขณะที่ วิเธอร์ส และชั่งน้ำหนัก 22 -35 กิโลกรัมกับร่างกายที่ค่อนข้างนานกว่าสูงและหางขนนกดี (หมายถึงมีจำนวนมากขนยาว) มักจะดำเนินการในช่วงโค้งกลับ หูมีขนยาวทิ่มชุดกว้างและโค้งมนเล็กน้อยที่ปลาย เสื้อมาในระยะยาว (Rauhaar) กลางและขนาดย่อม (Glatthaar) ทั้งกับเสื้อหนาแน่นกับทุกสีที่ได้รับอนุญาตให้มีสีขาวมีจุดสีน้ำตาล, สีแดง, สีดำหรือสีเทา",
                Image=@"\Images\Item-f7b499ce-937b-4eb0-8f07-faae141c9037.jpg",
                Description=@"Marita และฮีนซ์ Szobries เริ่มข้ามของพวกเขา Eurasiers และ Bobtails (เก่าอังกฤษอาจดี) ในปี 1987 เชื่อว่าถึงแม้จะแตกต่างกันมากในรายละเอียดสายพันธุ์ที่เป็นของประเภทที่คล้ายกันและเกิดขึ้นในขณะที่สายพันธุ์ภายใต้เงื่อนไขที่คล้ายกัน สุนัขจากกางเขนที่แสดงให้เห็นลักษณะที่ไม่ซ้ำกันและมีสุขภาพที่ดีได้รับการอบรมเพิ่มเติม เนื่องจากขาด Eurasiers เพียงพอที่สายพันธุ์ที่คล้ายกัน Chow Chow , ถูกเพิ่มเข้ามาและต่อมา Samoyeds และ Dalmatians ถูกเพิ่มเพื่อขยายฐานทางพันธุกรรม การปรับปรุงพันธุ์ได้อย่างต่อเนื่องโดยมุ่งเน้นในระยะยาวเกี่ยวกับมรดกของตัวละคร ชื่อ ""อีโล"" (เดิม Eloschaboro) จากตัวอักษรของสายพันธุ์ที่ 3 - Eurasier, หางสั้นและ Chow Chow-- และมีการป้องกันโดยเครื่องหมายการค้าในประเทศเยอรมนี สุนัขพันธุ์ที่มีชื่ออีโลได้รับอนุญาตเท่านั้นด้วยความยินยอมของผู้ก่อตั้งของสายพันธุ์อีโล",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of DogbreedsLetterESchema items.
        /// </summary>
        /// <returns>An observable collection of DogbreedsLetterESchema items.</returns>
        public ObservableCollection<Entities.DogbreedsLetterESchema> GetData(int numPage)
        {								
			return new ObservableCollection<Entities.DogbreedsLetterESchema>(_data.Skip(MaxResults * numPage).Take(MaxResults));
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of DogbreedsLetterESchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of DogbreedsLetterESchema items.</returns>
        public ObservableCollection<Entities.DogbreedsLetterESchema> Search(FilterSpecification filter)
        {
            return RepositoriesBase.Filter<Entities.DogbreedsLetterESchema>.FilterCollection(filter, _data);
        }
		
		/// <summary>
        /// Checks if data source has a element before the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a previous element, false if there is not</returns>
		public bool HasPrevious(Entities.DogbreedsLetterESchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) > 0;
        }
		
		/// <summary>
        /// Checks if data source has a element after the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a next element, false if there is not</returns>
		public bool HasNext(Entities.DogbreedsLetterESchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) < _data.Count - 1;
        }
		
		/// <summary>
        /// Retrieves the previous element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The previous element from items, if it exists. Otherwise, returns null</returns>
        public Entities.DogbreedsLetterESchema Previous(Entities.DogbreedsLetterESchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.First().Equals(current)) return null;

            return _data[_data.IndexOf(current) - 1];
        }
		
		/// <summary>
        /// Retrieves the next element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The next element from items, if it exists. Otherwise, returns null</returns>
        public Entities.DogbreedsLetterESchema Next(Entities.DogbreedsLetterESchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.Last().Equals(current)) return null;

            return _data[_data.IndexOf(current) + 1];
        }
	}
}

