// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   UnityContainer.tt
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using IIoc=WPAppStudio.Ioc.Interfaces;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Microsoft.Practices.Unity;
using Repositories=WPAppStudio.Repositories;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using Services=WPAppStudio.Services;
using ViewModels=WPAppStudio.ViewModel;

namespace WPAppStudio.Ioc
{
    //
    // Unity 2.1
    // http://msdn.microsoft.com/en-us/library/hh237493.aspx
    //
    // patterns & practices - Unity
    // http://unity.codeplex.com/
    //
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class Container : IIoc.IContainer
    {
        private readonly IUnityContainer _currentContainer;

        public Container()
        {
            _currentContainer = new UnityContainer();

            _currentContainer.RegisterType<IServices.ILiveTileService, Services.LiveTileService>();
			_currentContainer.RegisterType<IServices.ILockScreenService, Services.LockScreenService>();
			_currentContainer.RegisterType<IServices.IProximityService, Services.ProximityService>();
            _currentContainer.RegisterType<IServices.IDialogService, Services.DialogService>();
            _currentContainer.RegisterType<IServices.IShareService, Services.ShareService>();
			
            _currentContainer.RegisterType<IServices.ISpeechService, Services.SpeechService>();
            _currentContainer.RegisterType<IServices.INavigationService, Services.NavigationService>();
			
		
		    _currentContainer.RegisterType<IServices.IStorageService, Services.StorageService>();
			_currentContainer.RegisterType<IServices.IInternetService, Services.InternetService>(new ContainerControlledLifetimeManager());
            _currentContainer.RegisterType<IViewModels.IDogbreedsLetterA_ListViewModel, ViewModels.DogbreedsLetterA_ListViewModel>();
            _currentContainer.RegisterType<IViewModels.IDogbreedsLetterE_DetailViewModel, ViewModels.DogbreedsLetterE_DetailViewModel>();
            _currentContainer.RegisterType<IViewModels.IDogbreedsLetterD_DetailViewModel, ViewModels.DogbreedsLetterD_DetailViewModel>();
            _currentContainer.RegisterType<IViewModels.IDogbreedsLetterC_DetailViewModel, ViewModels.DogbreedsLetterC_DetailViewModel>();
            _currentContainer.RegisterType<IViewModels.IDogbreedsLetterB_DetailViewModel, ViewModels.DogbreedsLetterB_DetailViewModel>();
            _currentContainer.RegisterType<IViewModels.IDogbreedsLetterA_DetailViewModel, ViewModels.DogbreedsLetterA_DetailViewModel>();

			_currentContainer.RegisterType<IViewModels.IAboutViewModel, ViewModels.AboutViewModel>(new ContainerControlledLifetimeManager());
			_currentContainer.RegisterType<IViewModels.ILicenseViewModel, ViewModels.LicenseViewModel>(new ContainerControlledLifetimeManager());
			
			if (!System.ComponentModel.DesignerProperties.IsInDesignTool)
            {
				_currentContainer.RegisterType<Repositories.IDogbreedsLetterA_DogbreedsLetterA, Repositories.DogbreedsLetterA_DogbreedsLetterA>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IDogbreedsLetterB_DogbreedsLetterB, Repositories.DogbreedsLetterB_DogbreedsLetterB>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IDogbreedsLetterC_DogbreedsLetterC, Repositories.DogbreedsLetterC_DogbreedsLetterC>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IDogbreedsLetterD_DogbreedsLetterD, Repositories.DogbreedsLetterD_DogbreedsLetterD>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IDogbreedsLetterE_DogbreedsLetterE, Repositories.DogbreedsLetterE_DogbreedsLetterE>(new ContainerControlledLifetimeManager());
			}
			else
			{
				_currentContainer.RegisterType<Repositories.IDogbreedsLetterA_DogbreedsLetterA, Repositories.FakeDogbreedsLetterA_DogbreedsLetterA>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IDogbreedsLetterB_DogbreedsLetterB, Repositories.FakeDogbreedsLetterB_DogbreedsLetterB>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IDogbreedsLetterC_DogbreedsLetterC, Repositories.FakeDogbreedsLetterC_DogbreedsLetterC>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IDogbreedsLetterD_DogbreedsLetterD, Repositories.FakeDogbreedsLetterD_DogbreedsLetterD>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IDogbreedsLetterE_DogbreedsLetterE, Repositories.FakeDogbreedsLetterE_DogbreedsLetterE>(new ContainerControlledLifetimeManager());
			
			}
        }

        public T Resolve<T>()
        {
            return _currentContainer.Resolve<T>();
        }
    }
}
